In [1]:
import numpy as np

In [2]:
my_list = np.array([1, 2, 3])
my_list

array([1, 2, 3])

In [4]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5, 5)

array([[0.97224827, 0.16795585, 0.26626148, 0.6741817 , 0.02163479],
       [0.35296771, 0.82979314, 0.56590538, 0.5019054 , 0.51933302],
       [0.70829252, 0.30820747, 0.66092771, 0.31487045, 0.67822397],
       [0.80019488, 0.04240414, 0.25533523, 0.25555017, 0.78490823],
       [0.77040762, 0.60774066, 0.04988561, 0.61488967, 0.99285319]])

In [17]:
np.random.randn(2)

array([0.16407715, 0.52322931])

In [18]:
np.random.randn(5, 5)

array([[ 0.3195429 , -1.73082402,  0.57904146, -0.5461251 ,  0.57914615],
       [-1.48798626, -1.90728605,  1.26642269,  0.59681053, -1.63189694],
       [-0.35454937,  0.97062622, -0.1007467 , -0.14047509,  0.50724724],
       [ 0.5336376 , -1.97607981,  0.00945463,  0.31458181,  0.06538895],
       [-0.76720714,  0.16679381, -0.42304314,  0.19264228,  0.42221648]])

In [40]:
arr = np.random.randint(60, 101, 15)
arr

array([77, 70, 73, 68, 63, 90, 95, 77, 95, 81, 75, 81, 73, 72, 60])

In [42]:
arr[6:11] # start:stop:step

array([95, 77, 95, 81, 75])

In [48]:
test = [1, 2, 3, 4, 5]
test[1:4] = 100
test

[1, 100, 100, 100, 5]

In [46]:
arr[6:11] = 100
arr

array([ 77,  70,  73,  68,  63,  90, 100, 100, 100, 100, 100,  81,  73,
        72,  60])

In [49]:
arr = np.random.randint(60, 101, 16).reshape(4, 4)
arr

array([[85, 81, 88, 69],
       [84, 74, 88, 84],
       [67, 74, 97, 63],
       [60, 77, 84, 89]])

In [50]:
arr[2][2]

97

In [59]:
arr[:3][1:3]

array([[84, 74, 88, 84],
       [67, 74, 97, 63]])

In [61]:
arr[[1,3]]

array([[84, 74, 88, 84],
       [60, 77, 84, 89]])

In [63]:
arr[arr>80]

array([85, 81, 88, 84, 88, 84, 97, 84, 89])

In [64]:
arr + 3

array([[ 88,  84,  91,  72],
       [ 87,  77,  91,  87],
       [ 70,  77, 100,  66],
       [ 63,  80,  87,  92]])

In [65]:
arr / 8

array([[10.625, 10.125, 11.   ,  8.625],
       [10.5  ,  9.25 , 11.   , 10.5  ],
       [ 8.375,  9.25 , 12.125,  7.875],
       [ 7.5  ,  9.625, 10.5  , 11.125]])

In [67]:
np.sqrt(arr)

array([[9.21954446, 9.        , 9.38083152, 8.30662386],
       [9.16515139, 8.60232527, 9.38083152, 9.16515139],
       [8.18535277, 8.60232527, 9.8488578 , 7.93725393],
       [7.74596669, 8.77496439, 9.16515139, 9.43398113]])

In [68]:
np.sqrt([84])

array([9.16515139])